### ISSUE TITLE
Friendly inspection names

### ISSUE THREAD

**Issue by Danielss89** [Roave/RoaveDeveloperTools#18]
The FileRepository should include URL and a time for when the inspection happened.
and maybe just the MD5 part of the object "id".

**Comment by Ocramius** [comment]
The current view only shows links directly - the inspection ID must be that long because it's mainly an MD5 + unique ID + another MD5.

The name of the inspection itself may be produced by the list renderer by introspecting the serialized data...

**Comment by Danielss89** [comment]
ok, so the URL needs to be logged as well.

**Comment by Ocramius** [comment]
@Danielss89 it already happens in the [`RequestInspector`](https://github.com/Roave/RoaveDeveloperTools/blob/1b7051421815f84dd9466bd6209ade7d64140489/src/Roave/DeveloperTools/Mvc/Inspector/RequestInspector.php#L50) if the request is an HTTP request
