### ISSUE TITLE
Fatal: Allowed memory size of 134217728 bytes exhausted ...

### ISSUE THREAD

**Issue by nickurt** [Roave/RoaveDeveloperTools#34]
After enabling RDT in Zend ...

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 78 bytes) in [..]/vendor/zendframework/zendframework/library/Zend/Stdlib/ArrayUtils.php on line 255
```

**Comment by Danielss89** [comment]
Up your memory limit in php.ini

**Comment by Ocramius** [comment]
That is already quite high... I'll need to probably enable/disable some profiles conditionally

**Comment by Danielss89** [comment]
@Ocramius Do you think 134 mb is high?

**Comment by Ocramius** [comment]
It is for a small app...

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/
